name: "Publish Azure Web App"

on:
  push:
    branches:
      - main

env:
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: "8.0.x"
  AZURE_WEBAPP_PACKAGE_PATH: "Release"
  APP_NAME: bbon-file-info

jobs:
  build-and-publish:
    runs-on: Windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: dotnet restore
        run: dotnet restore
        working-directory: src/Example.FileInfoApp

      - name: dotnet build
        run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}
        working-directory: src/Example.FileInfoApp

      - name: dotnet publish
        run: |
          dotnet publish src/Example.FileInfoApp/Example.FileInfoApp.csproj -c Release -a x86 -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Example.FileInfoApp

      - name: Deploy Example.FileInfoApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "${{ env.APP_NAME }}"
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/Example.FileInfoApp"
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
